#!/usr/bin/env node
/**
 * Kinage brand mark → every derived asset, from ONE source.
 *
 *   design-system/brand/kinage-logo.svg   canonical lockup (supplied SVG, verbatim)
 *     ├─ src/assets/brand/kinage-logo-inverse.svg   same geometry, every fill white (footer)
 *     ├─ public/favicon.svg                          the four-quarter mark only, viewBox = its bounds
 *     └─ public/favicon-16.png, favicon-32.png, apple-touch-icon.png   (--png: rendered from favicon.svg)
 *
 * The lockup itself is imported straight from the canonical file by
 * components/Brand.tsx, so the header, footer and favicon cannot drift apart.
 *
 *   npm run brand          write the SVGs and PNGs
 *   node scripts/build-brand.mjs --check   fail when a derived SVG is out of date (part of `npm run check`)
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = resolve(root, 'design-system/brand/kinage-logo.svg');
const INVERSE = resolve(root, 'src/assets/brand/kinage-logo-inverse.svg');
const FAVICON = resolve(root, 'public/favicon.svg');
const check = process.argv.includes('--check');
const png = process.argv.includes('--png');

const source = readFileSync(SRC, 'utf8');
const paths = [...source.matchAll(/<path\b[^>]*\/>/g)].map((m) => m[0]);
const firstX = (p) => parseFloat(/\bd="M\s*(-?[\d.]+)/.exec(p)[1]);

// The mark is the four quarters left of the wordmark (x < 30 in the 151 × 34 lockup).
const mark = paths.filter((p) => firstX(p) < 30);
if (mark.length !== 4) throw new Error(`Expected 4 mark paths in ${SRC}, found ${mark.length}`);

// Bounds of the mark from its path coordinates (all segments are M/C/V/H/Z with absolute numbers).
const nums = mark.flatMap((p) => {
  const d = /\bd="([^"]+)"/.exec(p)[1];
  const out = [];
  let cmd = '';
  let i = 0;
  for (const tok of d.match(/[MCVHZLmcvhzl]|-?[\d.]+(?:e-?\d+)?/g)) {
    if (/[A-Za-z]/.test(tok)) {
      cmd = tok;
      i = 0;
      continue;
    }
    const v = parseFloat(tok);
    if (cmd === 'V') out.push([null, v]);
    else if (cmd === 'H') out.push([v, null]);
    else {
      out.push(i % 2 === 0 ? [v, null] : [null, v]);
      i += 1;
    }
  }
  return out;
});
const xs = nums.map(([x]) => x).filter((v) => v !== null);
const ys = nums.map(([, y]) => y).filter((v) => v !== null);
const fmt = (v) => +v.toFixed(4);
const [minX, maxX, minY, maxY] = [Math.min(...xs), Math.max(...xs), Math.min(...ys), Math.max(...ys)];
const size = Math.max(maxX - minX, maxY - minY);
const viewBox = `${fmt(minX - (size - (maxX - minX)) / 2)} ${fmt(minY - (size - (maxY - minY)) / 2)} ${fmt(size)} ${fmt(size)}`;

const header = '<!-- GENERATED by scripts/build-brand.mjs from design-system/brand/kinage-logo.svg — do not edit -->\n';
const inverse = header + source.replace(/fill="#[0-9A-Fa-f]{3,8}"/g, 'fill="#FFFFFF"');
const favicon = `${header}<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" fill="none">\n${mark.join('\n')}\n</svg>\n`;

const targets = [
  [INVERSE, inverse],
  [FAVICON, favicon],
];

if (check) {
  const stale = targets.filter(([file, body]) => !existsSync(file) || readFileSync(file, 'utf8') !== body);
  if (stale.length) {
    console.error(`✗ brand assets out of date: ${stale.map(([f]) => f.replace(root, '.')).join(', ')} — run \`npm run brand\`.`);
    process.exit(1);
  }
  console.log('✓ brand assets match design-system/brand/kinage-logo.svg');
} else {
  for (const [file, body] of targets) {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, body);
    console.log(`✓ wrote ${file.replace(root, '.')}`);
  }
  console.log(`  favicon viewBox ${viewBox} (mark bounds ${fmt(minX)}–${fmt(maxX)} × ${fmt(minY)}–${fmt(maxY)})`);
}

if (png && !check) {
  const { chromium } = await import('playwright-core');
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const svg = readFileSync(FAVICON, 'utf8');
  const render = async (px, file, background = 'transparent', inset = 0) => {
    const ctx = await browser.newContext({ viewport: { width: px, height: px }, deviceScaleFactor: 1 });
    const page = await ctx.newPage();
    await page.setContent(
      `<html><body style="margin:0;background:${background}"><div style="width:${px}px;height:${px}px;box-sizing:border-box;padding:${inset}px">${svg.replace('<svg ', '<svg width="100%" height="100%" ')}</div></body></html>`,
    );
    await page.screenshot({ path: resolve(root, file), omitBackground: background === 'transparent' });
    await ctx.close();
    console.log(`✓ wrote ./${file}`);
  };
  await render(16, 'public/favicon-16.png');
  await render(32, 'public/favicon-32.png');
  // iOS home-screen icon: opaque, with the platform's customary margin.
  await render(180, 'public/apple-touch-icon.png', '#ffffff', 28);
  await browser.close();
}
